name: larena CI runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the site in the larena/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/blog -v ${{ github.workspace }}/_site:/srv/blog/_site \
        blog/builder:latest /bin/bash -c "chmod -R 777 /srv/blog && blog build --future"
